FROM node:22-slim

WORKDIR /app

# 安装pnpm
RUN npm install -g pnpm

# 复制前端项目文件
COPY ./web ./

# 设置环境变量
ENV NEXT_PUBLIC_API_URL=http://backend:8000/api

# 安装依赖
RUN pnpm install

# 构建应用
RUN pnpm build

# 暴露端口
EXPOSE 3000

# 启动服务
CMD ["pnpm", "start"]
